feature/HU03
Miltonbel/misomobile2023 pull request #76
Opened 2023-05-04 18:04 UTC by luissanta

2023-05-06 21:13 UTC, FelipeGarcia01 commented on app/src/main/java/com/example/vinyls/model/network/NetworkServiceAdapter.kt
> +        requestQueue.add(getRequest("bands",
```suggestion
        requestQueue.add(getRequest("musicians",
```

2023-05-06 21:15 UTC, FelipeGarcia01 commented on app/src/main/java/com/example/vinyls/model/network/NetworkServiceAdapter.kt
> +        requestQueue.add(getRequest("bands",
La HU es consulta de artistas (Ruben blades, Oscar de Leon, Yan Collazos...) 

ese endpoint retorna bandas (Queen, Grupo niche, Gayacan....)

2023-05-06 21:16 UTC, FelipeGarcia01 commented on app/src/main/java/com/example/vinyls/model/Artist.kt
> +    val creationDate:String
Pilas, esta no es la estructura de un artista.... 

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/111367151/236646869-8e6c768f-8dc0-4c9e-96f8-9b9f38387dff.png">

2023-05-06 21:18 UTC, FelipeGarcia01 requested changes
Hay que corregir el modelo y el adapter, la estructura propuesta es de una banda no de un artista. 

![image](https://user-images.githubusercontent.com/111367151/236646928-6bcd7154-826f-4e33-b255-bb6e7efd06c2.png)

2023-05-06 23:12 UTC, luissanta commented on app/src/main/java/com/example/vinyls/model/network/NetworkServiceAdapter.kt
> +        requestQueue.add(getRequest("bands",
Resuelto

2023-05-06 23:12 UTC, luissanta commented on app/src/main/java/com/example/vinyls/model/Artist.kt
> +    val creationDate:String
Resuelto, revisa de nuevo

2023-05-08 23:33 UTC, FelipeGarcia01 approved these changes

2023-05-08 23:34 UTC, merged