Feature/add e2e
Miltonbel/misomobile2023 pull request #96
Opened 2023-05-25 06:53 UTC by FelipeGarcia01

Creadas pruebas 

![image](https://github.com/Miltonbel/misomobile2023/assets/111367151/3dc4d879-e1ca-4c52-b75c-f06138b63544)
![image](https://github.com/Miltonbel/misomobile2023/assets/111367151/024e6675-3003-4d8d-962d-6b078b51c7f5)
![image](https://github.com/Miltonbel/misomobile2023/assets/111367151/e409622b-1da5-4114-b639-e44abf16cacc)
![image](https://github.com/Miltonbel/misomobile2023/assets/111367151/bb41074d-1d20-4ffe-89da-f05739bb953e)
![image](https://github.com/Miltonbel/misomobile2023/assets/111367151/7ddee926-791d-4375-a208-30050a2ad634)
![image](https://github.com/Miltonbel/misomobile2023/assets/111367151/0267b818-15a5-447d-a6c4-9545aa6d37b0)
![image](https://github.com/Miltonbel/misomobile2023/assets/111367151/577f45b9-148a-4b9d-bbea-1c9bf05f0fdb)
![image](https://github.com/Miltonbel/misomobile2023/assets/111367151/7441f0f9-d2e4-4e7e-b06e-d446e4d5d771)

2023-05-25 12:38 UTC, Miltonbel requested changes

2023-05-25 12:38 UTC, Miltonbel commented on app/src/main/java/com/example/vinyls/model/network/NetworkServiceAdapter.kt
> +
Por favor ajustar la ip publica

2023-05-25 22:29 UTC, FelipeGarcia01 commented on app/src/main/java/com/example/vinyls/model/network/NetworkServiceAdapter.kt
> +
👍

2023-05-26 00:35 UTC, Miltonbel approved these changes

2023-05-26 00:36 UTC, luissanta approved these changes

2023-05-26 00:42 UTC, merged